pool:
  name: "Default"
trigger:
  - main
jobs:
  - job: myjob
    displayName: myjob
    steps:
     - task: Maven@3
       inputs:
         mavenPOMFile: 'pom.xml'
         publishJUnitResults: true
         goals: 'package'
         testResultsFiles: '**/surefire-reports/TEST-*.xml'
       
     - task: PublishBuildArtifacts@1
       inputs:
         PathtoPublish: '$(Build.Repository.LocalPath)' 
         ArtifactName: 'drop' 
         publishLocation: 'Container'    
    
   

